name: Set up Alejandra

on:
  push:
  pull_request:

permissions: read-all

jobs:
  install:
    name: Install Alejandra
    runs-on: ubuntu-20.04
    steps:
      - name: Download
        run: |
          wget https://github.com/kamadorueda/alejandra/releases/download/3.0.0/alejandra-x86_64-unknown-linux-musl
      - name: Makes her available in the environment
        run: |
          mv alejandra-x86_64-unknown-linux-musl alejandra
          chmod +x alejandra
          mv alejandra /usr/local/bin
